# Generated by Django 4.1.5 on 2023-01-09 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_confirmed', 'Not confirmed'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='not_confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_code', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
