# Generated by Django 4.1.4 on 2022-12-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='confirmation_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Not confirmed'), ('waiting', 'Waiting'), ('in_process', 'In process'), ('completed', 'Completed')], default='default value', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='student',
<<<<<<< HEAD
            field=models.ForeignKey(default='default value', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
>>>>>>> demo
        ),
    ]
