# Generated by Django 4.1.4 on 2023-01-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchase_status_alter_purchase_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Not confirmed'), ('waiting', 'Waiting'), ('completed', 'Completed')], default='not_confirmed', max_length=50),
        ),
    ]
