# Generated by Django 4.1.4 on 2023-01-03 15:06

import applications.profile_account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', applications.profile_account.models.UserManager()),
            ],
        ),
    ]
