# Generated by Django 4.1.4 on 2023-01-03 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseposter_rename_places_course_available_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
