# Generated by Django 4.1.4 on 2022-12-30 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_end_date_course_final_price_course_teacher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='CoursePoster',
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default='<django.db.models.fields.DecimalField>', max_digits=10),
        ),
    ]
