# Generated by Django 4.1.4 on 2023-01-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseposter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='courses.course'),
        ),
    ]
